<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://soap.ws.xsd.uttesh.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://soap.ws.xsd.uttesh.com/" name="HelloWebServiceService">
    <types>
        <xsd:schema>
            <xsd:import namespace="http://soap.ws.xsd.uttesh.com/" schemaLocation="SimpleProviderService.xsd"/>
        </xsd:schema>
    </types>
    <message name="PublishMessage">
        <part name="parameters" element="tns:PublishMessage"/>
    </message>
    <message name="PublishMessageResponse">
        <part name="parameters" element="tns:PublishMessageResponse"/>
    </message>
    <portType name="SimpleProviderService">
        <operation name="PublishMessage">
            <input wsam:Action="http://soap.ws.xsd.uttesh.com/SimpleProviderService/PublishMessage" message="tns:PublishMessage"/>
            <output wsam:Action="http://soap.ws.xsd.uttesh.com/SimpleProviderService/PublishMessageResponse" message="tns:PublishMessageResponse"/>
        </operation>
    </portType>
    <binding name="SimpleProviderServicePortBinding" type="tns:SimpleProviderService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="PublishMessage">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="SimpleProviderService">
        <port name="SimpleProviderServicePort" binding="tns:SimpleProviderServicePortBinding">
            <soap:address location="http://localhost:8080/soap-spring-xsd-ws/secure/soap/SimpleProviderService"/>
        </port>
    </service>
</definitions>